services:
  prometheus:
    image: prom/prometheus:v2.41.0
#    network_mode: host
#    extra_hosts: ['host.docker.internal:host-gateway']
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./data/prometheus/config:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - back-tier

#  grafana:
#    image: grafana/grafana-oss:8.5.16
#    pull_policy: always
##    network_mode: host
#    container_name: grafana
#    restart: unless-stopped
#    user: root
#    ports:
#      - 3000:3000 # access grafana url
#    networks:
#      - back-tier
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_USERS_ALLOW_SIGN_UP=false
#      - GF_SERVER_DOMAIN=localhost
#      # Enabled for logging
#      - GF_LOG_MODE=console file
#      - GF_LOG_FILTERS=alerting.notifier.slack:debug alertmanager:debug ngalert:debug

  demo:
    image: james-spring-boot-demo:v0.1
    container_name: james-basic-prometheus-example
    ports:
      - 8080:8080
    networks:
      - back-tier

networks:
  back-tier: